# Generated by Django 4.2 on 2024-08-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
