# Generated by Django 4.2 on 2024-08-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_alter_album_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='front_page',
            field=models.ImageField(upload_to='media/album_images/'),
        ),
    ]
